### ISSUE TITLE
Here we need to add component as shown in image

### ISSUE THREAD

**Issue by 0shivamh** [cwipedia-in/training.cwipedia#3]
![Screenshot 2022-10-06 at 18 20 06](https://user-images.githubusercontent.com/50539402/194317771-48c0c596-1d53-4883-8883-d49dc5747af4.png)

**Comment by amansingh1373** [comment]
@0shivamh i think i can work on this please assign me this task

**Comment by 0shivamh** [comment]
> @0shivamh i think i can work on this please assign me this task

sure...

**Comment by amansingh1373** [comment]
hey @0shivamh i am trying to setup node_modules folder so that i can run npm start but there seems to be an error which i cannot figure out kindly help me out. 
![error](https://user-images.githubusercontent.com/67228126/194385431-95df2528-0a61-4861-b99a-53e532f4455e.png)

**Comment by 0shivamh** [comment]
> hey @0shivamh i am trying to setup node_modules folder so that i can run npm start but there seems to be an error which i cannot figure out kindly help me out. ![error](https://user-images.githubusercontent.com/67228126/194385431-95df2528-0a61-4861-b99a-53e532f4455e.png)

use "react": "^17.0.2",

**Comment by amansingh1373** [comment]
@0shivamh there is still some error
![error](https://user-images.githubusercontent.com/67228126/194517062-019a83c7-f207-4e25-9171-c35bdc70933d.png)

**Comment by 0shivamh** [comment]
> @0shivamh there is still some error ![error](https://user-images.githubusercontent.com/67228126/194517062-019a83c7-f207-4e25-9171-c35bdc70933d.png)

comment out 2nd line

**Comment by AdarshBajpai67** [comment]
use git bash

**Comment by amansingh1373** [comment]
@0shivamh is this fine
![component](https://user-images.githubusercontent.com/67228126/194718730-6b7aa8c3-b111-474e-906c-bd928e7176a2.png)

**Comment by 0shivamh** [comment]
> @0shivamh is this fine ![component](https://user-images.githubusercontent.com/67228126/194718730-6b7aa8c3-b111-474e-906c-bd928e7176a2.png)

perfect, just change that explore icon

**Comment by amansingh1373** [comment]
@0shivamh i have changed it to a star cuz i couldn't find the circle star sorry about that
![new](https://user-images.githubusercontent.com/67228126/194730995-92bf10a6-fa67-423e-86d7-81d2148633aa.png)
is this fine .... if yes i have made a PR kindly merge it
